import React from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';

function Terms({ t }) {
  const siteUrl = 'https://decision-help-production.up.railway.app';
  return (
    <div className="about">
      <Helmet>
        <title>Terms of Service — Decision Help</title>
        <link rel="canonical" href={`${siteUrl}/terms`} />
        <meta name="description" content="Decision Help terms of service. Understand the rules and guidelines for using our free decision maker tool and services." />
        <meta property="og:title" content="Terms of Service — Decision Help" />
        <meta property="og:description" content="Terms and conditions for using Decision Help's free decision maker tool." />
        <meta property="og:url" content={`${siteUrl}/terms`} />
        <meta property="og:type" content="website" />
      </Helmet>
      <h1>Terms of Service</h1>
      <p className="page-subtitle">Last updated: June 28, 2026</p>

      <div className="about-section">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Decision Help ("the Site"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the Site or its services.</p>
      </div>

      <div className="about-section">
        <h2>2. Description of Service</h2>
        <p>Decision Help provides a free online decision maker tool that offers positive-bias suggestions to help users make choices. The Site includes multiple decision modes (This or That, Yes or No, Pick from List, Spin the Wheel), a community vote feed, a blog, and optional account features such as decision history and profile management.</p>
        <p>The service is provided "as is" and is intended for entertainment and personal guidance purposes only. Decisions generated by the tool should not replace professional advice.</p>
      </div>

      <div className="about-section">
        <h2>3. User Accounts</h2>
        <p>You may use the basic decision maker tool without creating an account. Optional account registration requires a valid email address and username. You are responsible for maintaining the confidentiality of your password and for all activities under your account.</p>
        <p>You must be at least 13 years of age to create an account. We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.</p>
      </div>

      <div className="about-section">
        <h2>4. Acceptable Use</h2>
        <p>You agree to use the Site only for lawful purposes. You must not:</p>
        <p>- Submit violent, hateful, sexually explicit, or otherwise inappropriate content<br/>
        - Attempt to manipulate, abuse, or spam the decision maker or voting systems<br/>
        - Use the Site to harass, stalk, or harm others<br/>
        - Attempt to gain unauthorized access to our systems or user accounts<br/>
        - Use automated tools, bots, or scripts to interact with the Site without express permission<br/>
        - Violate any applicable local, national, or international law</p>
        <p>We reserve the right to remove any content and ban any user who violates these rules, at our sole discretion.</p>
      </div>

      <div className="about-section">
        <h2>5. Content Ownership and License</h2>
        <p>You retain ownership of the questions, options, and decisions you submit. By submitting content to the Site (including public decisions), you grant Decision Help a non-exclusive, worldwide, royalty-free license to display, store, and share that content as part of the service.</p>
        <p>Users who make decisions public acknowledge that their username and decision may be visible to other users and may appear in the community feed.</p>
      </div>

      <div className="about-section">
        <h2>6. Intellectual Property</h2>
        <p>The Decision Help name, logo, design, and original content (excluding user-submitted content) are owned by Decision Help and protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our prior written consent.</p>
      </div>

      <div className="about-section">
        <h2>7. Disclaimer of Warranties</h2>
        <p>The Site and its services are provided on an "as is" and "as available" basis. We make no warranties, expressed or implied, regarding the reliability, accuracy, or availability of the service. Decision results are generated algorithmically and should be treated as suggestions, not professional advice.</p>
        <p>We do not guarantee that the Site will be uninterrupted, secure, or error-free, or that defects will be corrected.</p>
      </div>

      <div className="about-section">
        <h2>8. Limitation of Liability</h2>
        <p>In no event shall Decision Help, its operators, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Site, including but not limited to decisions made based on tool output, loss of data, or service interruptions.</p>
      </div>

      <div className="about-section">
        <h2>9. Third-Party Services</h2>
        <p>The Site integrates with third-party services including:</p>
        <p>- Google Analytics (usage tracking)<br/>
        - Google AdSense (advertising)<br/>
        - GIPHY (result GIFs)<br/>
        - PayPal (donations)</p>
        <p>These third parties have their own terms and policies. We are not responsible for their practices.</p>
      </div>

      <div className="about-section">
        <h2>10. Indemnification</h2>
        <p>You agree to indemnify and hold harmless Decision Help and its operators from any claims, damages, losses, liabilities, and expenses arising from your use of the Site, violation of these terms, or infringement of any third-party rights.</p>
      </div>

      <div className="about-section">
        <h2>11. Modifications to Terms</h2>
        <p>We reserve the right to modify these Terms of Service at any time. Changes will be posted on this page with an updated "Last updated" date. Continued use of the Site after changes constitutes acceptance of the new terms.</p>
      </div>

      <div className="about-section">
        <h2>12. Governing Law</h2>
        <p>These terms shall be governed by and construed in accordance with the laws, without regard to its conflict of law provisions. Any disputes relating to these terms shall be resolved in the appropriate courts.</p>
      </div>

      <div className="about-section">
        <h2>13. Contact</h2>
        <p>For questions about these Terms of Service, please contact us at gasmimohamed067@gmail.com or visit our <Link to="/about">About page</Link>.</p>
      </div>
    </div>
  );
}

export default Terms;
